author: Stephen Monroe (VioVioCity)
main: com.vioviocity.slammer.Slammer
name: Slammer
version: 1.0.1
commands:
  slam:
    description:
    usage: /<command> (player) (slammer), /<command> [list], /<command> [set|del] (slammer)
  free:
    description:
    usage: /<command> (player)
permissions:
  slammer.slam:
    description: Allows use of /slam (player) (slammer), also /free (player)
    default: op
  slammer.list:
    description: Allows use of /slam [list].
    default: op
  slammer.set:
    description: Allows use of /slam [set|del] (slammer)
    default: op